= Justin - Project Portfolio
ifdef::env-github,env-browser[:outfilesuffix: .adoc]
:imagesDir: ../images
:stylesDir: ../stylesheets

== Project: PocketBook
PocketBook is a desktop address book application targetted at Singaporeans. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10 kLoC.

*Code contributed*: [https://github.com/justintkj/main/blob/master/collated/main/justintkj.md[Functional code]] [https://github.com/justintkj/main/blob/master/collated/test/justintkj.md[Test code]]

=== Enhancement Added: Multiple Undo/Redo

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=undoredo]

#End of Extract#

---

==== Justification

When a large chunk of commands needs to be redone, it is inconvienent and inefficient to have to type the `undo` command. +
With an attached positive integer chosen by the user, user can redo alot of commands instantly with just one line of command. +
Original implementation of `undo` command is kept as it would be more inituitive for the user to not have to type the number of undos if only one is expected.

==== Implementation

---
UndoCommandParser : Accepts one more (optional) postive integer after the command `undo`. +
UndoCommand : Repeats the command for the requested number of times.

---

=== Enhancement Added: Sort

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=sort]

#End of Extract#

---

==== Justification

When the contacts list increases, the list of persons stored may be unorganized. +
Sorting is made possible for various type of parameters of users depending on the type of organization needed. +
The sort should be automatically updated in storage as it is inefficient for users who want a specified sort to need to type the same command everytime the application starts.


==== Implementation

---
#Start of Extract [from: Developer Guide]#

include::../DeveloperGuide.adoc[tag=sort]

#End of Extract#

---

=== Enhancement Added: Favourite

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=favourite]

#End of Extract#

---

==== Justification

When the contacts list increases, finding a person important to the user may be tough. +
Favourite hightlights a person name with a red box to highlight importance of the person, becoming prominent when scrolling through the list. +
A sort can be made to filter all the favourite persons to the top of the list, easier to find important persons.

==== Implementation

---
FavouriteCommandParser : Parses the valid argument (positive and valid indexes)
Favourite Command : Highlights the person chosen via model class to interact with the correct person.
Person : Contains a Favourite class as it's parameter. +
Favourite : Contains two different state, to highlight or not to highlight.
PersonCard : Updates highlight color for person.

---

=== Enhancement Added: Error Sound for invalid command

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=errorsound]

#End of Extract#

---

==== Justification

It is important to notify the user whenever an invalid command is given into the application. While the commandBox shows the type of error the user made,
it is essential to prompt the user with a sound to notify an error, following which, then reads the commandBox for type of error.
ErrorSound is called from ParseException and CommandException as a user's input which is rejected by the application would have to handle and error of these two types.

==== Implementation

---
ErrorSound : Creates a mediaplayer and play the sound file chosen.
ParseException : Calls invalidCommandSound() in Sound.
CommandException : Calls invalidCommandSound() in Sound.

---

=== Enhancement Added: Autocomplete 

==== External behavior

---
#Start of Extract [from: User Guide]#

include::../UserGuide.adoc[tag=autocomplete]

#End of Extract#

---

==== Justification

It reduces the amout of time needed to type a specified command and acts as a quick reference to a list of vaid command. 
When the user types a command in the CLI, recommended valid commmands are shown as a drop-down list for the user to choose.
User can choose from the list of valid command via the kbd:[Down Arrow] or kbd:[Up Arrow] and select via kbd:[Enter].
Valid commands needs to be saved and increase the drop down list to provide more relevant commands for the user progressively.
When XML file is deleted, a new XML file will be created, populated with a standard list of commands.

==== Implementation

---
CommandBox : Binds textfield with the CLI UI.
XMLAutocomplete : Updates the list when given valid command and to store the list in an XML file. A new XML file will be created with a sample list of basic inputs if XML file is deleted.

---

=== Enhancement Proposed: Add command `remark`

{Explain similar to the Undo/Redo feature above.}

=== Other contributions

* Updated the GUI color scheme (Pull requests https://github.com[#33], https://github.com[#34])
* Wrote additional tests to increase coverage from 88% to 92% (Pull requests https://github.com[#36], https://github.com[#38])

== Project: PowerPointLabs

{Optionally (not graded), you may include other projects in your portfolio.}
